---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= Astra Control REST API의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 새로운 기능, 개선 사항 및 버그 수정을 제공하기 위해 Astra Control REST API를 정기적으로 업데이트합니다.



== 2021년 8월 5일(21.08)

이 릴리스에는 새로운 Astra 배포 모델 및 REST API의 주요 확장이 포함되어 있습니다.



=== Astra Control Center 배포 모델

이 릴리즈에는 퍼블릭 클라우드 서비스로 제공되는 기존 Astra Control Service 오퍼링 외에도 Astra Control Center 온프레미스 구축 모델도 포함되어 있습니다. 사이트에 Astra Control Center를 설치하여 로컬 Kubernetes 환경을 관리할 수 있습니다. 두 Astra Control 배포 모델은 동일한 REST API를 공유하며, 설명서에 명시된 바와 같이 약간의 차이가 있습니다.



=== REST 리소스 유형의 확장

Astra Control REST API를 통해 액세스할 수 있는 리소스의 수가 크게 확장되었으며, 새로운 리소스 중 다수가 사내 Astra Control Center 오퍼링을 위한 기반을 제공하고 있습니다. 새로운 리소스에는 ASUP, 권한, 기능, 라이센스, 설정, 가입형, 버킷, 클라우드, 클러스터, 관리 클러스터, 스토리지 백엔드 및 스토리지 클래스 을 참조하십시오 link:../endpoints/resources.html["리소스"] 를 참조하십시오.



=== Astra 구축을 지원하는 추가 엔드포인트에는

확장된 REST 리소스 외에도 Astra Control 구축을 지원하는 데 사용할 수 있는 여러 가지 새로운 API 엔드포인트가 있습니다.

OpenAPI 지원:: OpenAPI 엔드포인트는 현재 OpenAPI JSON 문서 및 기타 관련 리소스에 대한 액세스를 제공합니다.
OpenMetrics 지원:: OpenMetrics 엔드포인트는 OpenMetrics 리소스를 통해 계정 메트릭에 액세스할 수 있습니다.




== 2021년 4월 15일(21.04)

이 릴리즈에는 다음과 같은 새로운 기능과 향상된 기능이 포함되어 있습니다.



=== REST API 소개

Astra Control REST API는 Astra Control Service 오퍼링과 함께 사용할 수 있습니다. REST 기술과 현재의 모범 사례를 기반으로 개발되었으며 API는 Astra 구축을 자동화하기 위한 기반을 제공하며 다음과 같은 기능과 이점을 제공합니다.

리소스:: 14개의 REST 리소스 유형을 사용할 수 있습니다.
API 토큰 액세스:: REST API에 대한 액세스는 Astra 웹 사용자 인터페이스에서 생성할 수 있는 API 액세스 토큰을 통해 제공됩니다. API 토큰은 API에 대한 보안 액세스를 제공합니다.
컬렉션 지원:: 리소스 컬렉션에 액세스하는 데 사용할 수 있는 다양한 쿼리 매개 변수 집합이 있습니다. 지원되는 일부 작업에는 필터링, 정렬 및 페이지 매김이 포함됩니다.

